
export const BAYQUNIYYAH_MATAN = [
  { id: 1, text: "أَبْدَأُ بِالْحَمْدِ مُصَلِّياً عَلَى * مُحَمَّدٍ خَيْرِ نَبِيٍّ أُرْسِلَا", translation: "Aku mulakan dengan pujian serta selawat ke atas Muhammad, sebaik-baik nabi yang diutuskan." },
  { id: 2, text: "وَذِي مِنْ أَقْسَامِ الْحَدِيثِ عِدَّهْ * وَكُلُّ وَاحِدٍ أَتَى وَحَدَّهْ", translation: "Ini adalah beberapa bahagian hadis, dan setiap satu datang dengan definisinya." },
  { id: 3, text: "أَوَّلُهَا الصَّحِيحُ وَهْوَ مَا اتَّصَلْ * إِسْنَادُهُ وَلَمْ يُشَذَّ أَوْ يُعَلّ", translation: "Yang pertama adalah Sahih, iaitu yang bersambung sanadnya, tidak syaz dan tidak pula ber'illah." },
  { id: 4, text: "يَرْوِيهِ عَدْلٌ ضَابِطٌ عَنْ مِثْلِهِ * مُعْتَمَدٌ فِي ضَبْطِهِ وَنَقْلِهِ", translation: "Diriwayatkan oleh perawi adil yang dhabit daripada yang seumpamanya, menjadi sandaran pada dhabit dan nukilannya." },
  { id: 5, text: "وَالْحَسَنُ الْمَعْرُوفُ طُرُقاً وَغَدَتْ * رِجَالُهُ لَا كَالصَّحِيحِ اشْتَهَرَتْ", translation: "Hasan adalah yang dikenali jalannya, namun perawinya tidaklah masyhur seperti perawi Sahih." },
  { id: 6, text: "وَكُلُّ مَا عَنْ رُتْبَةِ الْحُسْنِ قَصُرْ * فَهْوَ الضَّعِيفُ وَهْوَ أَقْسَاماً كُثُرْ", translation: "Dan setiap yang kurang daripada tahap Hasan, maka ia adalah Dha'if yang mempunyai banyak bahagian." },
  { id: 7, text: "وَمَا أُضِيفَ لِلنَّبِيِّ الْمَرْفُوعُ * وَمَا لِتَابِعٍ هُوَ الْمَقْطُوعُ", translation: "Apa yang disandarkan kepada Nabi adalah Marfu', manakala bagi Tabi'in adalah Maqtu'." },
  { id: 8, text: "وَالْمُسْنَدُ الْمُتَّصِلُ الْإِسْنَادِ مِنْ * رَاوِيهِ حَتَّى الْمُصْطَفَى وَلَمْ يَبِنْ", translation: "Musnad adalah yang bersambung sanadnya dari perawinya hingga Al-Mustafa (Nabi) tanpa terputus." },
  { id: 9, text: "وَمَا بِسَمْعِ كُلِّ رَاوٍ يَتَّصِلْ * إِسْنَادُهُ لِلْمُصْطَفَى فَالْمُتَّصِلْ", translation: "Dan apa yang didengar oleh setiap perawi yang bersambung sanadnya ke Al-Mustafa adalah Muttasil." },
  { id: 10, text: "مُسَلْسَلٌ قُلْ مَا عَلَى وَصْفٍ أَتَى * مِثْلُ أَمَا وَاللَّهِ أَنْبَانِي الْفَتَى", translation: "Musalsal adalah apa yang datang mengikut sifat tertentu, seperti: 'Demi Allah, pemuda itu telah memberitahu aku'." },
  { id: 11, text: "كَذَاكَ قَدْ حَدَّثَنِيهِ قَائِماً * أَوْ بَعْدَ أَنْ حَدَّثَنِي تَبَسَّمَا", translation: "Begitu juga (sifat perawi): 'Dia menceritakan kepadaku sambil berdiri', atau selepas menceritakan dia tersenyum." },
  { id: 12, text: "عَزِيزُ مَرْوِي اثْنَيْنِ أَوْ ثَلَاثَهْ * مَشْهُورُ مَرْوِي فَوْقَ مَا ثَلَاثَهْ", translation: "Aziz adalah hadis yang diriwayatkan oleh dua atau tiga orang, Masyhur diriwayatkan lebih daripada tiga orang." },
  { id: 13, text: "مُعَنْعَنٌ كَعَنْ سَعِيْدٍ عَنْ كَرَمْ * وَمُبْهَمٌ مَا فِيْهِ رَاوٍ لَمْ يُسَمْ", translation: "Mu'an'an pula seperti 'daripada Said daripada Karam', manakala Mubham adalah hadis yang di dalamnya terdapat perawi yang tidak dinamakan." },
  { id: 14, text: "وَكُلُّ مَا قَلَّتْ رِجَالُهُ عَلَا * وَضِدُّهُ ذَاكَ الَّذِي قَدْ نَزَلَا", translation: "Dan setiap yang sedikit perawinya adalah 'Ali (sanad tinggi), manakala lawannya adalah Nazil (sanad rendah)." },
  { id: 15, text: "وَمَا أَضَفْتَهُ إِلَى الْأَصْحَابِ مِنْ * قَوْلٍ وَفِعْلٍ فَهْوَ مَوْقُوفٌ زُكِنْ", translation: "Dan apa yang kamu sandarkan kepada para sahabat (al-ashab) daripada perkataan dan perbuatan, ia dikenali sebagai Mawquf." },
  { id: 16, text: "وَمُرْسَلٌ مِنْهُ الصَّحَابِيُّ سَقَطْ * وَقُلْ غَرِيْبٌ مَا رَوَى رَاوٍ فَقَطْ", translation: "Mursal pula adalah hadis yang gugur padanya Sahabat. Katakanlah: Gharib adalah apa yang diriwayatkan oleh seorang perawi sahaja." },
  { id: 17, text: "وَكُلُّ مَا لَمْ يَتَّصِلْ بِحَالِ * إِسْنَادُهُ مُنْقَطِعُ الْأَوْصَالِ", translation: "Dan setiap yang tidak bersambung sanadnya dalam apa jua keadaan, maka sanadnya adalah Munqati'." },
  { id: 18, text: "وَالْمُعْضَلُ السَّاقِطُ مِنْهُ اثْنَانِ * وَمَا أَتَى مُدَلَّساً نَوْعَانِ", translation: "Mu'dal pula adalah yang gugur padanya dua perawi. Hadis Mudallas pula terbahagi kepada dua jenis." },
  { id: 19, text: "الْأَوَّلُ الْإِسْقَاطُ لِلشَّيْخِ وَأَنْ * يَنْقُلَ عَمَّنْ فَوْقَهُ بِعَنْ وَأَنْ", translation: "Pertama, menggugurkan guru dan menukilkan daripada orang di atas gurunya dengan lafaz 'an' dan 'an'." },
  { id: 20, text: "وَالثَّانِ لَا يُسْقِطُهُ لَكِنْ يَصِفْ * أَوْصَافَهُ بِمَا بِهِ لَا يَنْعَرِفْ", translation: "Kedua, tidak menggugurkan guru tetapi menyifatkannya dengan sifat-sifat yang tidak dikenali." },
  { id: 21, text: "وَمَا يُخَالِفْ ثِقَةٌ بِهِ الْمَلَا * فَالشَّاذُّ وَالْمَقْلُوبُ قِسْمَانِ تَلَا", translation: "Apa yang diriwayatkan oleh perawi thiqah yang menyalahi orang ramai adalah Shadh. Maqlub pula ada dua bahagian." },
  { id: 22, text: "إِبْدَالُ رَاوٍ مَا بِرَاوٍ قِسْمُ * وَقَلْبُ إِسْنَادٍ لِمَتْنٍ قِسْمُ", translation: "Menggantikan seorang perawi dengan perawi lain adalah satu bahagian, dan menukarkan sanad bagi sesebuah matan adalah satu bahagian lain." },
  { id: 23, text: "وَالْفَرْدُ مَا قَيَّدْتَهُ بِثِقَةِ * أَوْ جَمْعٍ أَوْ قَصْرٍ عَلَى رِوَايَةِ", translation: "Al-Fard adalah apa yang kamu kaitkan dengan perawi thiqah, atau kumpulan tertentu, atau terhad pada riwayat tertentu." },
  { id: 24, text: "وَمَا بِعِلَّةٍ غُمُوضٍ أَوْ خَفَا * مُعَلَّلٌ عِنْدَهُمُ قَدْ عُرِفَا", translation: "Dan apa yang mempunyai 'illah yang kabur atau tersembunyi dikenali sebagai Mu'allal di sisi mereka." },
  { id: 25, text: "وَذُو اضْطِرَابٍ عِنْدَ أَهْلِ الْفَنِّ * اخْتِلَافُ سَنَدٍ أَوْ مَتْنِ", translation: "Hadis Mudtarib di sisi ahli seni hadis adalah perselisihan pada sanad atau matan." },
  { id: 26, text: "وَالْمُدْرَجَاتُ فِي الْحَدِيثِ مَا أَتَتْ * مِنْ بَعْضِ أَلْفَاظِ الرُّوَاةِ اتَّصَلَتْ", translation: "Mudraj dalam hadis adalah apa yang datang daripada sebahagian lafaz perawi yang bersambung dengan matan." },
  { id: 27, text: "وَمَا رَوَى كُلُّ قَرِينٍ عَنْ أَخِهْ * مُدَبَّجٌ فَاعْرِفْهُ حَقًّا وَانْتَخِهْ", translation: "Apa yang diriwayatkan oleh rakan sebaya daripada rakannya ialah Mudabbaj, maka kenalilah ia dengan benar." },
  { id: 28, text: "مُتَّفِقٌ لَفْظاً وَخَطًّا مُتَّفِقْ * وَضِدُّهُ فِيمَا ذَكَرْنَا الْمُفْتَرِقْ", translation: "Muttafiq adalah yang sama lafaz dan tulisannya, dan lawannya adalah Muftariq." },
  { id: 29, text: "مُؤْتَلِفٌ مُتَّفِقُ الْخَطِّ فَقَطْ * وَضِدُّهُ مُخْتَلِفٌ فَاخْشَ الْغَلَطْ", translation: "Mu'talif pula hanya sama pada tulisan sahaja, dan lawannya Mukhtalif, maka berhati-hatilah daripada tersilap." },
  { id: 30, text: "وَالْمُنْكَرُ الْفَرْدُ بِهِ رَاوٍ غَدَا * تَعْدِيلُهُ لَا يَحْمِلُ التَّفَرُّدَا", translation: "Munkar pula ialah hadis yang diriwayatkan secara bersendirian oleh perawi yang tarafnya tidak boleh diterima secara bersendirian." },
  { id: 31, text: "مَتْرُوكُهُ مَا وَاحِدٌ بِهِ انْفَرَدْ * وَأَجْمَعُوا لِضَعْفِهِ فَهْوَ كَرَدْ", translation: "Matruk pula adalah hadis yang diriwayatkan oleh seorang perawi sahaja dan ulama sepakat akan kelemahannya, maka ia tertolak." },
  { id: 32, text: "وَالْكَذِبُ الْمُخْتَلَقُ الْمَصْنُوعُ * عَلَى النَّبِيِّ فَذَلِكَ الْمَوْضُوعُ", translation: "Dan kedustaan yang direka serta dibuat-buat ke atas Nabi, itulah hadis Mawdu'." },
  { id: 33, text: "وَقَدْ أَتَتْ كَالْجَوْهَرِ الْمَكْنُونِ * سَمَّيْتُهَا مَنْظُومَةَ الْبَيْقُونِي", translation: "Ia telah datang bagaikan permata yang tersimpan, aku namakannya Manzumah Al-Bayquni." },
  { id: 34, text: "فَوْقَ الثَّلَاثِينَ بِأَرْبَعٍ أَتَتْ * أَقْسَامُهَا تَمَّتْ بِخَيْرٍ خُتِمَتْ", translation: "Tiga puluh empat jumlah baitnya, telah sempurna dengan kebaikan sebagai penutup." }
];

export const APP_THEME = {
  primary: '#064e3b',
  secondary: '#065f46',
  accent: '#c5a059',
  background: '#f0fdf4',
};
